name: 'Local Cache'
description:
  'Local cache solution designed for self-hosted runners, without relying on
  GitHub remote cache'
author: 'Your Name'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  path:
    description: 'List of files, directories, or wildcard patterns to cache'
    required: true
  key:
    description: 'Unique key for restoring and saving the cache'
    required: true
  restore-keys:
    description:
      'List of fallback keys to use for restoring the cache, ordered by priority'
    required: false
  upload-chunk-size:
    description: 'Size of upload chunks in MB'
    required: false
    default: '32'
  enableCrossOsArchive:
    description: 'Whether to enable cross-OS cache archives'
    required: false
    default: 'false'
  fail-on-cache-miss:
    description: 'Whether to fail when cache is not found'
    required: false
    default: 'false'
  lookup-only:
    description: 'Only lookup cache without restoring'
    required: false
    default: 'false'
  compression-level:
    description: 'zstd compression level (-5 to 22)'
    required: false
    default: '3'

# Define your outputs here.
outputs:
  cache-hit:
    description:
      'String value indicating whether a cache was found that exactly matches
      the key'
  cache-primary-key:
    description:
      'Primary key used to save the cache, typically used for separate restore
      and save operations'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/save.js'
  post-if: "success()"
