name: 'Restore Cache'
description: 'Restore local cache'
author: 'Your Name'

inputs:
  path:
    description: 'List of files, directories, or wildcard patterns to cache'
    required: true
  key:
    description: 'Unique key for restoring and saving the cache'
    required: true
  restore-keys:
    description:
      'List of fallback keys to use for restoring the cache, ordered by priority'
    required: false
  enableCrossOsArchive:
    description: 'Whether to enable cross-OS cache archives'
    required: false
    default: 'false'
  fail-on-cache-miss:
    description: 'Whether to fail when cache is not found'
    required: false
    default: 'false'
  lookup-only:
    description: 'Only lookup cache without restoring'
    required: false
    default: 'false'

outputs:
  cache-hit:
    description:
      'String value indicating whether a cache was found that exactly matches
      the key'
  cache-primary-key:
    description: 'Primary key used for subsequent save operations'

runs:
  using: 'node20'
  main: '../dist/restore.js'
